
title: "DevCave"
email: "tuaemail@example.com"
description: >-
  Blog italiano su informatica, cybersicurezza e programmazione.
  Scopri guide, strumenti e risorse utili.
baseurl: ""
url: "https://devcave.github.io"
locale: "it-IT"

theme: minimal-mistakes-jekyll

author:
  name: "Il tuo nome"
  avatar: "/assets/images/logo.png" # inserisci qui il tuo logo

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header:
  overlay_image: /assets/images/logo.png
  overlay_filter: 0.0
  show_overlay_logo: true
